name: hitchride
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  conditional_parent_widget: ^0.0.2
  day_night_time_picker: ^1.3.0
  dio: ^5.1.1
  fade_shimmer: ^2.2.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.6.4
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.0
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^8.0.0
  flutter_signin_button: ^2.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_api_availability: ^5.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.5
  google_nav_bar: ^5.0.6
  hooks_riverpod: ^2.3.6
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^0.8.9
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  logger: ^1.3.0
  marquee: ^2.2.3
  mime: ^1.0.4
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.3.1
  rename: ^2.1.1
  retrofit: ^4.0.1
  shimmer: ^3.0.0
  tuple: ^2.0.1
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.5
  build_runner_core: ^7.2.9
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.7

dependency_overrides:
  logging: 1.2.0
  intl: 0.18.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/styles/
    - assets/json/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
