// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHHsIEsGec8RIIIGe8V13PNnoy899XSeE',
    appId: '1:99693078149:web:8f94c43b97a574c4aaabec',
    messagingSenderId: '99693078149',
    projectId: 'c2c-ehailing',
    authDomain: 'c2c-ehailing.firebaseapp.com',
    databaseURL: 'https://c2c-ehailing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c2c-ehailing.appspot.com',
    measurementId: 'G-B3T1CWDJMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARdNVGBV4e4yuW4fyPnwPdexjmca7bjNE',
    appId: '1:99693078149:android:931f669afe2c441aaaabec',
    messagingSenderId: '99693078149',
    projectId: 'c2c-ehailing',
    databaseURL: 'https://c2c-ehailing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c2c-ehailing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSjwWR3ZIwGwL6NXAu1NyR1V-TEv-jrrw',
    appId: '1:99693078149:ios:981bbd65e8f5c44faaabec',
    messagingSenderId: '99693078149',
    projectId: 'c2c-ehailing',
    databaseURL: 'https://c2c-ehailing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c2c-ehailing.appspot.com',
    iosClientId: '99693078149-hj79vv6sdlklb90i91k5q34cqt1m6phb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehailingFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSjwWR3ZIwGwL6NXAu1NyR1V-TEv-jrrw',
    appId: '1:99693078149:ios:981bbd65e8f5c44faaabec',
    messagingSenderId: '99693078149',
    projectId: 'c2c-ehailing',
    databaseURL: 'https://c2c-ehailing-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'c2c-ehailing.appspot.com',
    iosClientId: '99693078149-hj79vv6sdlklb90i91k5q34cqt1m6phb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehailingFrontend',
  );
}
